### ISSUE TITLE
Add functionality to select underlying taxonomy

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/CAMIProfilingVisualization#1]
The input profiles have TaxID's. These TaxID's are used by `ete3` to construct the taxonomic tree. The currently implemented code automatically downloads the NCBI taxdump and translates these taxID's to names, positions on trees etc. However, the input profiles may be old (so contain TaxID's that have been depreciated by NCBI taxdump), or have TaxID's that don't exist in the NCBI taxdump (such as strain TaxID's eg: 1234.5).

Should add the following functionality:
- [x] add an option to use __only__ the input profile(s) taxID's to construct the tree
- [x] by default, use `ete3` NCBI taxdump to construct the tree (already done)
- [x] add functionality such that if the default is used, `ete3` checks to see if the newest NCBI taxdump is being used
- [x] add functionality to manually use your own NCBI taxdump. (i.e. find where `ete3` is placing their NCBI taxdump with the files like `names.dmp`, `nodes.dmp` etc.) and let the user put their own taxdump in this location. Motivation is sometimes you want to peg the taxonomy to a very specific point in time.

**Comment by jaquejbrito** [comment]
ete3 doesn't look to have an option to check the taxdump file version. 
I've added an option to enable the user to update the database.
