### ISSUE TITLE
Packaging and distribution

### ISSUE THREAD

**Issue by dkoslicki** [dkoslicki/CAMIProfilingVisualization#10]
Provide installation (in order of importance):
- [x] PyPi (hence `pip install`)
- [x] Bioconda. An example recipe can be found [here](https://github.com/dkoslicki/CMash/blob/master/dev/conda/meta.yaml). I can help walk you through this if you have any issues with it.

**Comment by Addicted-to-coding** [comment]
https://pypi.org/project/CAMIViz/0.1/

**Comment by dkoslicki** [comment]
Note @Addicted-to-coding that the plot isn't showing up on the PyPi site. May want to give a plain English explanation if it's difficult to include a file/plot.

**Comment by Addicted-to-coding** [comment]
Done!

**Comment by dkoslicki** [comment]
Great, thanks @Addicted-to-coding ! I hate to move the goalposts on this one, but we will also need to make a Galaxy toolshed release (as promised in the ABACBS letter). I imagine this will be a "last item" to do, but it would be good for you and @jaquejbrito to familiarize yourselves in how to do this so it can be done easily once we are production-ready

**Comment by Addicted-to-coding** [comment]
Galaxy toolshed release:https://toolshed.g2.bx.psu.edu/view/vsarwal/tampa/a744c6d53e69
